### ISSUE TITLE
Problemas con test3

### ISSUE THREAD

**Issue by mariaGit2324** [mariaGit2324/practica_dwec_gestor_presupuesto#1]
Hola @pedroprieto, no me pasa el test3 en la función de Agrupación de Gastos y me estoy volviendo loca para resolverlo. A ver si puedes echarle un vistazo y darme alguna pista. 

Muchas gracias! 

Este es el error que me sale: 
> practica_dwec_gestor_presupuesto@1.0.0 test3
> mocha test/03_testIntroJSIII.cy.js

  Función CrearGasto y funcionamiento de objeto gasto
    ✔ Método 'obtenerPeriodoAgrupacion' del objeto gasto

  Función filtrarGastos
    ✔ Filtra los gastos (variable global 'gastos') de acuerdo con los parámetros pasados a la función       

  Función agruparGastos
    1) Realiza una agrupación de gastos por períodos temporales

  2 passing (7ms)
  1 failing

  1) Función agruparGastos
       Realiza una agrupación de gastos por períodos temporales:

      La opción de agrupar por mes no funciona.
      + expected - actual

      -0
      +3

**Comment by pedroprieto** [comment]
Difícil de pillar... El problema está en el valor por defecto que le das a `etiquetas`:
https://github.com/mariaGit2324/practica_dwec_gestor_presupuesto/blob/c182d5fc10f59933a1599536bf966c5a1c015ed1/js/gestionPresupuesto.js#L171

Eso hace que tu función de filtrado por etiquetas no funcione correctamente. No pongas el valor por defecto y funcionará.

Un saludo!

**Comment by mariaGit2324** [comment]
Ohhhh ya funciona!! Muchas gracias!
